/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StockService } from "../stock.service";
import { StockCreateInput } from "./StockCreateInput";
import { Stock } from "./Stock";
import { StockFindManyArgs } from "./StockFindManyArgs";
import { StockWhereUniqueInput } from "./StockWhereUniqueInput";
import { StockUpdateInput } from "./StockUpdateInput";
import { StockPriceFindManyArgs } from "../../stockPrice/base/StockPriceFindManyArgs";
import { StockPrice } from "../../stockPrice/base/StockPrice";
import { StockPriceWhereUniqueInput } from "../../stockPrice/base/StockPriceWhereUniqueInput";

export class StockControllerBase {
  constructor(protected readonly service: StockService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Stock })
  async createStock(@common.Body() data: StockCreateInput): Promise<Stock> {
    return await this.service.createStock({
      data: data,
      select: {
        createdAt: true,
        id: true,
        market: true,
        name: true,
        sector: true,
        symbolField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Stock] })
  @ApiNestedQuery(StockFindManyArgs)
  async stocks(@common.Req() request: Request): Promise<Stock[]> {
    const args = plainToClass(StockFindManyArgs, request.query);
    return this.service.stocks({
      ...args,
      select: {
        createdAt: true,
        id: true,
        market: true,
        name: true,
        sector: true,
        symbolField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Stock })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async stock(
    @common.Param() params: StockWhereUniqueInput
  ): Promise<Stock | null> {
    const result = await this.service.stock({
      where: params,
      select: {
        createdAt: true,
        id: true,
        market: true,
        name: true,
        sector: true,
        symbolField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Stock })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStock(
    @common.Param() params: StockWhereUniqueInput,
    @common.Body() data: StockUpdateInput
  ): Promise<Stock | null> {
    try {
      return await this.service.updateStock({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          market: true,
          name: true,
          sector: true,
          symbolField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Stock })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStock(
    @common.Param() params: StockWhereUniqueInput
  ): Promise<Stock | null> {
    try {
      return await this.service.deleteStock({
        where: params,
        select: {
          createdAt: true,
          id: true,
          market: true,
          name: true,
          sector: true,
          symbolField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/stockPrices")
  @ApiNestedQuery(StockPriceFindManyArgs)
  async findStockPrices(
    @common.Req() request: Request,
    @common.Param() params: StockWhereUniqueInput
  ): Promise<StockPrice[]> {
    const query = plainToClass(StockPriceFindManyArgs, request.query);
    const results = await this.service.findStockPrices(params.id, {
      ...query,
      select: {
        closePrice: true,
        createdAt: true,
        date: true,
        highPrice: true,
        id: true,
        lowPrice: true,
        openPrice: true,

        stock: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        volume: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/stockPrices")
  async connectStockPrices(
    @common.Param() params: StockWhereUniqueInput,
    @common.Body() body: StockPriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stockPrices: {
        connect: body,
      },
    };
    await this.service.updateStock({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/stockPrices")
  async updateStockPrices(
    @common.Param() params: StockWhereUniqueInput,
    @common.Body() body: StockPriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stockPrices: {
        set: body,
      },
    };
    await this.service.updateStock({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/stockPrices")
  async disconnectStockPrices(
    @common.Param() params: StockWhereUniqueInput,
    @common.Body() body: StockPriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      stockPrices: {
        disconnect: body,
      },
    };
    await this.service.updateStock({
      where: params,
      data,
      select: { id: true },
    });
  }
}
